### ISSUE TITLE
may cause the connection to end prematurely

### ISSUE THREAD

**Issue by xxxsen** [AdguardTeam/gomitmproxy#13]
https://github.com/AdguardTeam/gomitmproxy/blob/c7fb1711772b738d3f89b55615b6ac0c8e312367/proxy.go#L410

before entering the `copyConnectTunnel` logic, it should reset the ctx deadline, otherwise even if the remote server has been sending data back to the user, but the user side has not read any data(from browser or any other app), it will cause the connection to be interrupted abnormally(read deadline and return).

**Comment by ameshkov** [comment]
The current deadlines logic seems wrong in general.

For now I've removed the timeout by default.
